# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: '一站式micro:bit学习平台'
site_description: 'ElecFreaks Product Document'
site_author: 'Will'
site_url: 'https://www.elecfreaks.com/learn-cn/'

# Repository
repo_name: 'Microbit'
repo_url: 'https://github.com/elecfreaks/learn-cn'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 ElecFreaks'

# Theme directory
theme_dir: material

# Icon
#site_favicon: 'docs/images/favicon.ico'
site_favicon: https://raw.githubusercontent.com/elecfreaks/learn-cn/master/docs/images/favicon.ico

# Configuration
theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    primary: light green
    accent: 'indigo'    
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/favicon.ico'
  search:
    language: 'cn'
    tokenizer: '[\s\-\.]+'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/elecfreaks/learn-cn'
    - type: 'facebook'
      link: 'https://www.facebook.com/ElecFreaksTech/'
    #- type: 'linkedin'
    #  link: 'https://linkedin.com/in/squidfunk'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.keys

# Page tree
pages:
  - 欢迎来到micro:bit知识库: 'index.md'

  - makecode系列教程:
    - BBC micro:bit: Micro_bit_Board.md
    
  - Python系列教程:
    - 1 准备开始Micropython学习: 
          - 1.1 什么是Microbit: micropython1_1.md
          - 1.2 什么是Python: micropython1_2.md
          - 1.3 工具及环境: micropython1_3.md
          - 1.4 小结: micropython1_4.md
    - 2 第一个MicroPython案例: 
          - 2.1 Hello world: micropython2_1.md
          - 2.2 Python中的程序结构: micropython2_2.md
          - 2.3 Python中的基础语法: micropython2_3.md
          - 2.4 什么是API: micropython2_4.md
    - 3 LED点阵显示屏: 
          - 3.1 Python中的数据类型和变量: micropython3_1.md
          - 3.2 Python中的运算符: micropython3_2.md
          - 3.3 显示屏的相关API: micropython3_3.md
          - 3.4 演示案例: micropython3_4.md
          - 3.5 课后练习: micropython3_5.md
    - 4 A+B独立按键: 
          - 4.1 Python中的循环语句: micropython4_1.md
          - 4.2 Python中的条件语句: micropython4_2.md
          - 4.3 按键相关API: micropython4_3.md
          - 4.4 演示案例: micropython4_4.md
          - 4.5 课后练习: micropython4_5.md
    - 5 输入输出IO口: 
          - 5.1 什么是输入输出引脚: micropython5_1.md
          - 5.2 PWM及相关API: micropython5_2.md
          - 5.3 演示案例: micropython5_3.md
          - 5.4 课后练习: micropython5_4.md
          
  - micro:bit 模组:
    - 面包板扩展板（breadboard:bit）: Micro_bit_Breadboard_Adapter_CN.md
    - 5V传感器扩展板（octopus:bit）: Octopus_bit_CN.md
    - 3V传感器扩展板（sensor:bit）: Sensor_bit.md
    - 两路电机驱动板（motor:bit）: Motor_bit_V16.md
    - 钮扣电池扩展板（power:bit）: Power_bit_CN.md
    - 3路IO带电池盒扩展板（ring:bit）: Ring_bit_CN.md
    - 3路IO基础扩展板（basic:bit）: Basic_bit_CN.md
    - mBot扩展版: 
          - mBot扩展版介绍: Robit_CN.md
          - 案例01：超声波测距: Robit_Case_01.md
          - 案例02：超声波避障: Robit_Case_02.md
          - 案例03：永不坠落的小车: Robit_Case_03.md
          - 案例04：巡线: Robit_Case_04.md
          - 案例05：倒车报警: Robit_Case_05.md
          - 案例06：彩虹LED: Robit_Case_06.md
          - 案例07：自动车灯: Robit_Case_07.md
    - 金手指扩展板(edge:bit): edge_bit_CN.md
    - Micro:bit 电源模块: Micro_bit_Power_Supply_Module_3.3V_2A_CN.md

  - Micro:bit 套件:
     - micro:bit 基础套件: 
          - 基础套件简介: basic_kit.md
          - 3路IO基础扩展板（basic:bit）: Basic_bit_CN.md
     - micro:bit 小小科学家套件:
          - Micro:bit 小小科学家套件: Micro_bit_Starter_Kit.md
          - 课程_01 LED: Micro_bit_Starter_Kit_Lesson_01_LED_CN.md
          - 课程_02 按钮: Micro_bit_Starter_Kit_Lesson_02_Button_CN.md
          - 课程_03 电位器: Micro_bit_Starter_Kit_Lesson_03_Trimpot_CN.md
          - 课程_04 光敏电阻: Micro_bit_Starter_Kit_Lesson_04_Photocell_CN.md
          - 课程_05 三色LED: Micro_bit_Starter_Kit_Lesson_05_RGB_LED_CN.md
          - 课程_06 自锁开关: Micro_bit_Starter_Kit_Lesson_06_Self_lock_Switch_CN.md
          - 课程_07 温度传感器: Micro_bit_Starter_Kit_Lesson_07_Temperature_Sensor_CN.md
          - 课程_08 舵机: Micro_bit_Starter_Kit_Lesson_08_Servo_CN.md
          - 课程_09 蜂鸣器: Micro_bit_Starter_Kit_Lesson_09_Buzzer_CN.md
          - 课程_10 电机: Micro_bit_Starter_Kit_Lesson_10_Motor_CN.md
          - 课程_11 七彩灯环: Micro_bit_Starter_Kit_Lesson_11_Rainbow_LED_CN.md
          - 课程_12 加速度计: Micro_bit_Starter_Kit_Lesson_12_Accelerometer_CN.md
          - 课程_13 指南针: Micro_bit_Starter_Kit_Lesson_13_Compass_CN.md
          - 课程_14 环境光: Micro_bit_Starter_Kit_Lesson_14_Ambient_Light_CN.md
     - Micro:bit 小小发明家套件: 
          - Micro:bit 小小发明家套件: Micro_bit_Tinker_Kit.md
          - 音乐播放器: Micro_bit_Tinker_Kit_Case_01_Music_Machine_CN.md
          - 智能灯: Micro_bit_Tinker_Kit_Case_02_Smart_Light_CN.md
          - 电子琴: Micro_bit_Tinker_Kit_Case_03_Electro_Theremin_CN.md
          - 报警装置: Micro_bit_Tinker_Kit_Case_04_Simple_Alarm_Box_CN.md
          - 土壤湿度检测: Micro_bit_Tinker_Kit_Case_05_Plant_Monitoring_Device_CN.md
          - 入侵检测: Micro_bit_Tinker_Kit_Case_06_Intruder_Detection_CN.md
          - 喂鱼器: Micro_bit_Tinker_Kit_Case_07_Fish_Feeder_CN.md
          - 运动检测: Micro_bit_Tinker_Kit_Case_08_Motion_Detector_CN.md
          - 测谎仪: Micro_bit_Tinker_Kit_Case_09_Lie_Detector_CN.md
          - 乒乓球游戏: Micro_bit_Tinker_Kit_Case_10_PADDLEBALLSUPERSMASHEM_CN.md
          - 躲避小行星: Micro_bit_Tinker_Kit_Case_11_Avoid_Asteroids_CN.md
          - 遥控小车: Micro_bit_Tinker_Kit_Case_12_Remote_Control_Everything_CN.md
          - micro:bit小车: Micro_bit_Tinker_Kit_Case_13_Micro_Bit_Car_CN.md
          - 抛煎饼游戏: Micro_bit_Tinker_Kit_Case_14_Flipping_Pancakes_CN.md
          - 跑迷宫游戏: Micro_bit_Tinker_Kit_Case_15_Maze_Runner_CN.md
          - 速算游戏: Micro_bit_Tinker_Kit_Case_16_QUICK_MATHS_CN.md
          - 猜音调游戏: Micro_bit_Tinker_Kit_Case_17_Pitch_Perfect_CN.md
          - 手指灵敏度游戏: Micro_bit_Tinker_Kit_Case_18_Finger_Dexterity_CN.md
          - 电子水平仪: Micro_bit_Tinker_Kit_Case_19_Electric_Spirit_Level_CN.md
          - 太空射击游戏: Micro_bit_Tinker_Kit_Case_20_Space_Shooter_CN.md
          - 飞行的小鸟游戏: Micro_bit_Tinker_Kit_Case_21_Flappy_Bird_CN.md
          - 摩尔斯代码信息传输: Micro_bit_Tinker_Kit_Case_22_Wire_Transmission_CN.md
          - 贪吃蛇游戏: Micro_bit_Tinker_Kit_Case_23_Snake_Game_CN.md
          
          
     - Micro:bit 带电池盒套件: 
          - Micro:bit 带电池盒套件: Micro_bit_Board_with_Battery_Holder_kit.md
     - Ring:bit 小车套件: 
          - Ring:bit 小车套件: Ring_bit_Car_Kit_CN.md
          - 案例_01 添加代码库: Ring_bit_Car_Kit_Case_01_Add_Package_CN.md
          - 案例_02 折线行走: Ring_bit_Car_Kit_Case_02_S_Walk_CN.md
          - 案例_03 画圆: Ring_bit_Car_Kit_Case_03_Draw_a_Circel_CN.md
          - 案例_04 无线遥控: Ring_bit_Car_Kit_Case_04_Wireless_Remote_Control_CN.md
          
  - Micro:bit 传感器与配件:
    - 蓝色电位器电子积木: Octopus_Analog_Rotation_Brick_Blue.md
    - 3线宽压超声波模块: sonar_bit.md
    - 两路巡线模块电子积木: Tracking_Module.md
    - 2xAA 无盖电池盒: 2xAA_Battery_Holder_without_Cover.md
    - 2xAA 有盖带开关电池盒: 2xAA_Battery_Holder_With_ON_OFF_Switch_and_Cover.md
    - micro:bit外壳: Micro_case_CN.md
    - micro:bit外壳带AA电池盒: Acrylic_Case_with_Two_AA_Battery_Holder.md
    - Motor:bit小车底盘: Smart_Car_Chassis_for_motor_bit_CN.md 
# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'
